### ISSUE TITLE
Question: plugins/alerta-web and dashboard url

### ISSUE THREAD

**Issue by jjh74** [alerta/alerta-contrib#274] opened 2019-07-05 16:25 UTC
Hi,

Plugins create url/link to alerta (web)ui with something like
```url = "%s/#/alert/%s" % (DASHBOARD_URL, alert.id) #msteams ```
and this creates an url like https://example.org/#/alert/b8f62e01-50f6-4bf5-b13a-4462e9789067

Should '#' (in path) work with current alerta-web (7.0.x) ? For me the url works without /#/ but not with /#/ (goes to "all" alerts instead of opening that one specific alert) ?

**Comment by satterly** [comment] 2019-07-05 17:09
It should work. This code block is meant to convert old URL links to new ... https://github.com/alerta/alerta-webui/blob/master/src/router.ts#L182-L190

**Comment by jjh74** [comment] 2019-07-05 17:56
Thanks, I'll take a look(probably next week) and see if I can figure out what's happening. At the moment if for example msteams has a link https://example.org/#/alert/9bd2bd57-448e-4767-9a71-99edd3d49275 and I click on the link I get redirected to https://example.org/alerts#dateRange:,;sb:undefined;sd:0
(I have zero knowledge of vue.js so any tips are welcome:)

**Comment by satterly** [comment] 2019-07-05 18:26
Oh. That's almost certainly a bug. I wrote the router redirect before I started work on storing filter and sort settings in the hash so there's probably a conflict there. I'll take a look too.

**Comment by satterly** [comment] 2019-07-05 21:43
The conflicting router redirect was caused by the introduction of the catch-all route to `/alerts`. This should be fixed by moving the hash mode redirect to before the catch-all redirect. See alerta/alerta-webui#211

**Closed** 2019-07-05 21:44 UTC
Labels: bug
